apps/front/models.py
from exts import db
import shortuuid
from werkzeug.security import generate_password_hash, check_password_hash
from datetime import datetime


# 用户注册
class FrontUser(db.Model):
    __tabelname__ = 'front_user'
    id = db.Column(db.String(100), primary_key=True, default=shortuuid.uuid)
    DL_ID = db.Column(db.String(6), nullable=False, unique=True)
    username = db.Column(db.String(50), nullable=False)
    _password = db.Column(db.String(200), nullable=False)
    # 头像
    avatar = db.Column(db.String(100))
    join_time = db.Column(db.DateTime, default=datetime.now)

    # def __init__(self, *args, **kwargs):
    #     if "password" in kwargs:
    #         self.password = kwargs.get('password')
    #         kwargs.pop("password")
    #     super(FrontUser, self).__init__(*args, **kwargs)

    def __init__(self, DL_ID, username, password):
        self.DL_ID = DL_ID
        self.username = username
        self.password = password

    @property
    def password(self):
        return self._password

    @password.setter
    def password(self, newpwd):
        self._password = generate_password_hash(newpwd)

    def check_password(self, rawpwd):
        # print(generate_password_hash(rawpwd))
        # print(check_password_hash(self._password, rawpwd))
        return check_password_hash(self._password, rawpwd)


# 日志数据库模型
class IT_SysRunSupport(db.Model):
    # __bind_key__ = 'DLXX'
    __tablename__ = 'IT_SysRunSupport'
    Id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    NeederId = db.Column(db.String(8), nullable=True)
    NeedTime = db.Column(db.DateTime, default=datetime.now)
    Type = db.Column(db.Integer)
    Kind = db.Column(db.String(3))
    Sys = db.Column(db.Integer)
    Part = db.Column(db.Integer)
    NeedDesc = db.Column(db.String(200))
    Reson = db.Column(db.String(100))
    Process = db.Column(db.String(200))
    Result = db.Column(db.String(50))
    BeginTime = db.Column(db.DateTime)
    EndTime = db.Column(db.DateTime)
    WorkHours = db.Column(db.DECIMAL(5, 2))
    DealerId = db.Column(db.String(2))
    Dealers = db.Column(db.String(20))
    Tool = db.Column(db.Integer)

    # RegDate = db.Column(db.DateTime, default=datetime.now)

    def __init__(self, NeederId, NeedTime, Type, Kind, Sys, Part, NeedDesc, Reson, Process, Result,
                 BeginTime, EndTime, WorkHours, DealerId, Dealers, Tool):
        # self.Id = Id
        self.NeederId = NeederId
        self.NeedTime = NeedTime
        self.Kind = Kind
        self.Type = Type
        self.Sys = Sys
        self.Part = Part
        self.NeedDesc = NeedDesc
        self.Reson = Reson
        self.Process = Process
        self.Result = Result
        self.BeginTime = BeginTime
        self.EndTime = EndTime
        self.DealerId = DealerId
        self.Dealers = Dealers
        self.Tool = Tool
        # self.RegDate = RegDate
        self.WorkHours = WorkHours


# 服务分类数
class IT_SysRunSupportKind(db.Model):
    # __bind_key__ = 'DLXX'
    __tablename__ = 'IT_SysRunSupportKind'
    Id = db.Column(db.String(3), primary_key=True)
    Name = db.Column(db.String(16))
    Type = db.Column(db.Integer)
    Hours = db.Column(db.DECIMAL(5, 2))

    # CopyHours = db.Column(db.Boolean)

    def __init__(self, Id, Name, Type, Hours):
        self.Id = Id
        self.Name = Name
        self.Type = Type
        self.Hours = Hours
        # self.CopyHours = CopyHours


# 服务类型数据库模型
class IT_SysServiceType(db.Model):
    # __bind_key__ = 'DLXX'
    __tablename__ = 'IT_SysServiceType'
    id = db.Column(db.Integer, primary_key=True)
    service_type = db.Column(db.String(50))

    def __init__(self, id, service_type):
        self.id = id
        self.service_type = service_type

apps/front/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField, SelectField, DateField, \
    TextAreaField, TimeField, DateTimeField
from wtforms.validators import DataRequired, EqualTo, length
from .models import IT_SysRunSupportKind as IT_kind, IT_SysServiceType as IT_type, FrontUser
from flask import Blueprint
from sqlalchemy import create_engine
from flask import g
from exts import db
from config import DB_URI
from sqlalchemy.orm import sessionmaker


# 注册表单
class RegisterForm(FlaskForm):
    username = StringField('用户名', validators=[DataRequired(), length(1, 16)], render_kw={'class': 'form-control'})
    DL_ID = StringField('工号', validators=[DataRequired(), length(6)], render_kw={'class': 'form-control'})
    password = PasswordField('密码', validators=[DataRequired(), length(8, 16)], render_kw={'class': 'form-control'})
    password_repeat = PasswordField('密码', validators=[DataRequired(), length(8, 16), EqualTo('password')],
                                    render_kw={'class': 'form-control'})
    submit = SubmitField('注册', render_kw={'class': 'btn btn-primary'})


class SearchForm(FlaskForm):
    search = StringField('搜索框', render_kw={'class': 'form-control me-2', 'placeholder': '别搜了，还用不了呢~'})
    submit = SubmitField('搜索一哈', render_kw={'class': 'btn btn-primary'})


# 登陆表单
class LoginForm(FlaskForm):
    DL_ID = StringField('用户名', validators=[DataRequired(), length(6, message='请输入6位工号')],
                        render_kw={'class': 'form-control'})
    password = PasswordField('密码', validators=[DataRequired(), length(8, 16, message='请输入6-20位密码')],
                             render_kw={'class': 'form-control'})
    remember = BooleanField('记住密码')
    submit = SubmitField('登录', render_kw={'class': 'btn btn-primary'})


# conn = engine.connect()
# sql = 'From '
# sql1 =
# conn.execute('')

# 查询服务类型和服务分类列表，在get请求里会有上下文
# for type in IT_type.query.with_entities(IT_type.service_type).all():
#     types = types + list(type)
#
# for name in IT_kind.query.with_entities(IT_kind.Name).all():
#     names = names + list(name)
engine = create_engine(DB_URI)
session = sessionmaker(engine)()


# 日志表单
class JournalForm(FlaskForm):
    types = ['--请选择--']
    names = ['--请选择--']
    for type in session.query(IT_type.service_type).all():
        types = types + list(type)
    for name in session.query(IT_kind.Name).all():
        names = names + list(name)

    service_type = SelectField('服务类型', validators=[DataRequired()], choices=types,
                               render_kw={'class': 'btn btn-primary dropdown-toggle dropdown-toggle-split'})

    start_time = TimeField('起始时间', validators=[DataRequired()], render_kw={'class': 'btn btn-primary'})

    service_classification = SelectField('服务分类', validators=[DataRequired()], choices=names,
                                         render_kw={
                                             'class': 'btn btn-primary dropdown-toggle dropdown-toggle-split'})

    # end_hours = TimeField('小时')
    end_time = TimeField('结束时间', validators=[DataRequired()], render_kw={'class': 'btn btn-primary'})
    hours = StringField('工时', validators=[DataRequired()], render_kw={'class': 'btn btn-primary'})
    problem_description = TextAreaField('问题描述', render_kw={'class': 'form-control'})
    cause_analysis = TextAreaField('原因分析', render_kw={'class': 'form-control'})
    process1 = TextAreaField('处理过程', render_kw={'class': 'form-control'})
    result = TextAreaField('处理结果', render_kw={'class': 'form-control'})
    submit = SubmitField('提交', render_kw={'class': 'btn btn-primary clearfix'})

apps/front/__init__.py
import apps.front.hooks

apps/front/views.py
from flask import (Blueprint,
                   views,
                   render_template,
                   request,
                   session,
                   redirect,
                   url_for,
                   flash,
                   g,
                   jsonify)
from .forms import RegisterForm, LoginForm, SearchForm, JournalForm
import config
from exts import db
from .models import FrontUser, IT_SysRunSupportKind as IT_kind, IT_SysRunSupport as IT_support, \
    IT_SysServiceType as IT_type
from .decorators import login_required
from sqlalchemy import create_engine
from datetime import datetime
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TimeField, SelectField, TextAreaField
from wtforms.validators import DataRequired

# 创建蓝图，指定子域名
front_bp = Blueprint('front', __name__)


# 主页面
@front_bp.route('/')
@login_required
def index():
    form = SearchForm()
    return render_template('front/front_index.html', form=form)


# 作者简介
@front_bp.route('/itta/')
@login_required
def itta():
    return render_template('front/front_Introduction_to_the_author.html')


# 注销
@front_bp.route('/logout/')
@login_required
def logout():
    del session[config.FRONT_USER_ID]
    # session.clear()
    return redirect(url_for('front.login'))


# 日志
@front_bp.route('/write/', methods=['GET', 'POST'])
@login_required
def write():
    # types = ['--请选择--']
    # names = ['--请选择--']
    # # 查询服务类型和服务分类列表，在get请求里会有上下文
    # for type in IT_type.query.with_entities(IT_type.service_type).all():
    #     types = types + list(type)
    #
    # for name in IT_kind.query.with_entities(IT_kind.Name).all():
    #     names = names + list(name)
    # print(types)
    # print(names)
    form = JournalForm()
    if form.submit.data and form.validate_on_submit():
        NeederId = ''
        NeedTime = datetime.now()
        Type = IT_kind.query.with_entities(IT_kind.Type).filter_by(Name=form.service_classification.data).first()[0]
        Kind = IT_kind.query.with_entities(IT_kind.Id).filter_by(Name=form.service_classification.data).first()[0]
        Sys = 0
        Part = 0
        NeedDesc = form.problem_description.data
        Reson = form.cause_analysis.data
        Process = form.process1.data
        Result = form.result.data
        BeginTime = datetime.strptime(f"{datetime.now().strftime('%Y-%m-%d')}" + f" {form.start_time.data}",
                                      "%Y-%m-%d %H:%M:%S")
        EndTime = datetime.strptime(f"{datetime.now().strftime('%Y-%m-%d')}" + f" {form.end_time.data}",
                                    "%Y-%m-%d %H:%M:%S")
        WorkHours = form.hours.data
        DealerId = 'A1'
        Dealers = g.front_user.username
        Tool = 0
        journal = IT_support(NeederId, NeedTime, Type, Kind, Sys, Part,
                             NeedDesc, Reson, Process, Result, BeginTime, EndTime, WorkHours,
                             DealerId, Dealers, Tool)
        db.session.add(journal)
        db.session.commit()
        flash('提交成功')
        return redirect(url_for('front.write'))
    elif request.method == 'POST':
        # 调用ajax.js
        data = request.get_json()
        name = data['name']

        class_ = []
        # 子查询找到服务类型对应的服务分类
        id = IT_type.query.with_entities(IT_type.id).filter(IT_type.service_type == name).all()[0][0]
        for cls in IT_kind.query.with_entities(IT_kind.Name).filter(IT_kind.Type == id).all():
            class_ = list(cls) + class_
        return jsonify(class_)
    return render_template('front/front_journal_write.html', form=form)


# 个人中心
@front_bp.route('/profile/')
@login_required
def profile():
    return render_template('front/front_user_base.html')


# 登录
class LoginView(views.MethodView):
    def __init__(self):
        self.form = LoginForm()

    def get(self, message=None):
        # flash(message)
        return render_template('front/front_login.html', message=message, form=self.form)

    def post(self):
        # form = LoginForm(request.form)

        if self.form.validate_on_submit():
            DL_ID = self.form.DL_ID.data
            password = self.form.password.data
            remember = self.form.remember.data
            user = FrontUser.query.filter_by(DL_ID=DL_ID).first()
            # print(user.username)
            if user and user.check_password(password):
                session[config.FRONT_USER_ID] = user.id
                if remember:
                    # 如果设置记住我，session.permanent = True
                    # 那么cookie过期时间31天
                    session.permanent = True
                return redirect(url_for('front.index'))
            else:
                return self.get(message='工号或者密码错误')
        # else:
        #     print(self.form.errors)
        #     # ('password',['请输入6-20位密码'])
        #     message = self.form.get_error()
        #     return self.get(message=message)


# 注册
class RegView(views.MethodView):
    def __init__(self):
        self.form = RegisterForm()

    def get(self, message=None):
        return render_template('front/front_reg.html', message=message, form=self.form)

    def post(self):
        if self.form.validate_on_submit():
            username = self.form.username.data
            DL_ID = self.form.DL_ID.data
            password = self.form.password.data
            # 校验账号是否存在
            if FrontUser.query.filter(FrontUser.DL_ID == DL_ID):
                return self.get(message='此工号已经存在')
            else:
                user = FrontUser(DL_ID=DL_ID, username=username, password=password)
                db.session.add(user)
                db.session.commit()
        return redirect(url_for('front.login'))


front_bp.add_url_rule('/login/', view_func=LoginView.as_view('login'))
front_bp.add_url_rule('/reg/', view_func=RegView.as_view('reg'))

templates/front/front_404.html
{% extends 'front/front_base.html' %}

{% block title %}404 - Page Not Found{% endblock %}

{% block content %}
<h1>Page Not Found</h1>
<p>You are lost...</p>
{% endblock %}

templates/front/front_500.html
{% extends 'front/front_base.html' %}

{% block title %}500 - Internal Server Error{% endblock %}

{% block content %}
<h1>Internal Server Error</h1>
<p>Something was wrong...</p>
{% endblock %}

templates/front/front_Introduction_to_the_author.html
{% extends 'front/front_base.html' %}
{#{% from 'macros.html' import qux %}#}
{% block styles %}
    {{ super() }}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='front/css/itta.css' ) }}">
{% endblock %}
{% block content %}
    {% set user='Liu Ruochen' %}
    <hea1der>
        <h1>作者简介</h1>
        <h3>刘若晨</h3>
        <h5>智能制造部</h5>
        <h5>应用支持岗</h5>
        <h2>
            <img src="{{ url_for('static', filename='front/sys_img/Bai.jpg') }}" width="300">
        </h2>
    </hea1der>

    <footer>
        <small>{{ b }}</small>
    </footer>
{% endblock %}
{% block footer %}
    {{ super() }}
    <small>
        /{{ s }}
    </small>
{% endblock %}

templates/front/front_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}11:40{% endblock %}</title>
        <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='front/sys_img/tsunami.svg') }}">
        <!-- 新 Bootstrap5 核心 CSS 文件 -->
        <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/5.1.1/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='front/css/base.css' ) }}">

        <!--  popper.min.js 用于弹窗、提示、下拉菜单 -->
        <script src="https://cdn.staticfile.org/popper.js/2.9.3/umd/popper.min.js"></script>

        <!-- 最新的 Bootstrap5 核心 JavaScript 文件 -->
        <script src="https://cdn.staticfile.org/twitter-bootstrap/5.1.1/js/bootstrap.min.js"></script>

        {% block styles %}
        {% endblock %}
    {% endblock %}
</head>

<body>
{#navbar栏#}
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-lg-2">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">
            <img src="{{ url_for('static', filename='front/sys_img/tsunami.svg') }}" alt="" width="30" height="24">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            {% block nav_bar %}
            {% endblock %}
            </ul>
        </div>
        <div class="navbar-nav-right" id="navbarNav-right">
            <ul class="navbar-nav">
                {% block nav_bar_right %}
                {% endblock %}
            </ul>
        </div>
    </div>
</nav>

{#main栏#}
<div class="main">
    <div class="container-fluid">
        {#        {% for message in get_flashed_messages() %}#}
        {#            <div class="alert">{{ message }}</div>#}
        {#        {% endfor %}#}
        {% block content %}{% endblock %}
    </div>
</div>

{#footer栏#}
<div class="footer ">
    <div class="container-fluid">
        <div class="inf">
            {% block footer %}
                <small>
                    <ul class="nav justify-content-center mt-lg-2">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page"
                               href="#">&copy; 2021-2022</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page"
                               href="{{ url_for('front.itta') }}" title="Written by RC Liu">Liu
                                Ruochen</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="https://github.com/Helloch3n" title="Fork me on GitHub">GitHub</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="https://blog.csdn.net/Helloch3n?spm=1000.2115.3001.5343"
                               title="Fork me on CSDN">CSDN</a>
                        </li>
                    </ul>
                </small>
            {% endblock %}
        </div>
    </div>
</div>
{% block scripts %}

{% endblock %}
</body>
</html>

templates/front/front_index.html
{% extends 'front/front_base.html' %}
{#{% from 'macros.html' import qux %}#}
{#{% from 'macros.html' import form_field %}#}

{% block styles %}
    {{ super() }}
    {#    <link rel="stylesheet" href="{{ url_for('static',filename='bootstrap-4.6.1-dist/css/bootstrap.css') }}">#}
    {#    <link rel="stylesheet" href="https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/4.6.1/css/bootstrap.css">#}
    <link rel="stylesheet" href="{{ url_for('static',filename='front/css/index.css') }}">
{% endblock %}

{% block nav_bar %}
    {{ super() }}
    {#    <li class="nav-item">#}
    {#        <a class="nav-link active" aria-current="page" href="#">数据查询</a>#}
    {#    </li>#}
    <ul class="navbar-nav">
    <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{{ url_for('front.index') }}">Home</a>
    </li>
    <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="#">还没想好呢</a>
    </li>
    {#    <li class="nav-item">#}
    {#        <a class="nav-link active" aria-current="page" href="#">论坛</a>#}
    {#    </li>#}
    {#    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDarkDropdown"#}
    {#            aria-controls="navbarNavDarkDropdown" aria-expanded="false" aria-label="Toggle navigation">#}
    {#        <span class="navbar-toggler-icon"></span>#}
    {#    </button>#}
    {#    <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">#}
    <ul class="navbar-nav">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button"
               data-bs-toggle="dropdown" aria-expanded="false">
                管理
            </a>
            <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                <li><a class="dropdown-item" href="#">信息化项目</a></li>
                <li><a class="dropdown-item" href="{{ url_for('front.write') }}">系统运维</a></li>
                <li><a class="dropdown-item" href="#">分类服务统计</a></li>
                <li><a class="dropdown-item" href="#">设备台账</a></li>
                <li><a class="dropdown-item" href="#">月度工作计划</a></li>
                <li><a class="dropdown-item" href="#">系统维护帮助</a></li>
                <li><a class="dropdown-item" href="#">加班-换休</a></li>
                <li><a class="dropdown-item" href="#">数据检查</a></li>
            </ul>
        </li>
    </ul>
    {#    </div>#}
{% endblock %}
{% block nav_bar_right %}
    <li class="nav-item"><a class="nav-link active" aria-current="page"
                            href="{{ url_for('front.profile') }}">{{ g.front_user.username }}</a></li>
    <li class="nav-item"><a class="nav-link active" aria-current="page" href="{{ url_for('front.logout') }}">注销</a></li>
{% endblock %}
{% block content %}
    <div class="main">
        <div class="container-fluid mx-auto">
            <div class="justify-content-center">
                <label class="visually-hidden" for="specificSizeInputGroupUsername">关键词</label>
                <div class="input-group">
                    {{ form.csrf_token }}
                    <div class="input-group-text">
                        <img src="{{ url_for('static', filename='front/sys_img/search.svg') }}" class="img-fluid"
                             alt="主题图片">
                    </div>
                    {#                    <input type="text" class="form-control" id="specificSizeInputGroupUsername" placeholder="关键词...">#}
                    {{ form.search }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/front/front_journal_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/front/front_journal_write.html
{% extends 'front/front_index.html' %}
{#{% from 'macros.html' import form_field %}#}
{% from 'common/_macros.html' import render_field %}
{% block styles %}
    {#    {{ super() }}#}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='front/css/journal.css') }}">
{% endblock %}
{% block content %}
    {% for message in get_flashed_messages() %}
    <div class="alert alert-primary text-center" role="alert">{{ message }}</div>
    {% endfor %}
    <div class="main">
        <form action="" method="post">
            <div class="mx-auto clearfix" style="max-width:80%">
                <div class="clearfix">
                    {{ form.csrf_token }}
                    {{ render_field(form.service_type,onchange="Select('service_type','#service_classification','/write/',csrf)") }}
                    {#            {{ form.service_type }}#}
                    {{ form.start_time.label }}
                    {{ form.start_time }}
                </div>
                <div class="clearfix">
                    {{ form.csrf_token }}
                    {{ form.service_classification.label }}
                    {{ form.service_classification }}
                    {#                {{ form.end_hours.label }}#}
                    {#                {{ form.end_hours }}#}
                    {{ form.end_time.label }}
                    {{ form.end_time }}
                    {{ form.hours.label }}
                    {{ form.hours }}
                </div>
            </div>
            <div class="mx-auto clearfix" style="max-width:80%;height: 600px">
                <div class="input-group h-25">
                    <span class="input-group-text">问题描述</span>
                    {{ form.problem_description }}
                </div>
                <br>
                <div class="input-group h-25">
                    <span class="input-group-text">原因分析</span>
                    {{ form.cause_analysis }}
                </div>
                <br>
                <div class="input-group h-25">
                    <span class="input-group-text">处理过程</span>
                    {{ form.process1 }}
                </div>
                <br>
                <div class="input-group h-25">
                    <span class="input-group-text">处理结果</span>
                    {{ form.result }}
                </div>
            </div>
            <br>
            <div class="mx-auto clearfix" style="max-width:0;margin: 70px">
                {{ form.submit }}
            </div>
        </form>
    </div>
{% endblock %}
{% block scripts %}
    <script type="text/javascript">
        var school_url = "{{ url_for('front.write') }}";
        var csrf = "{{ csrf_token() }}";
    </script>
    <script src="https://cdn.bootcdn.net/ajax/libs/jquery/3.6.0/jquery.js"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='front/js/script.js') }}"
            charset="UTF-8"></script>
{% endblock %}

templates/front/front_login.html
{% extends 'front/front_base.html' %}
{#{% from 'macros.html' import form_field %}#}
{% block styles %}
    {{ super() }}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='front/css/reg_log.css') }}">
{% endblock %}
{% block content %}
    <form method="post">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
        {{ form.csrf_token }}
        <div class="mb-3">
            <label for="DL_ID" class="form-label">工号</label>
            {{ form.DL_ID }}
            {#            <div id="emailHelp" class="form-text">We'll never share your username with anyone else.</div>#}
        </div>
        <div class="mb-3">
            <label for="password" class="form-label">密码</label>
            {{ form.password }}
        </div>
        {% if message %}
            <p class="text-danger" style="text-align:center">{{ message }}</p>
        {% endif %}
        <div class="mb-3 form-check">
            <input type="checkbox" class="form-check-input" id="exampleCheck1" name="remember" value="1">
            <label class="form-check-label" for="exampleCheck1">记住我</label>
        </div>
        {{ form.submit }}<br>
        <a href="{{ url_for('front.reg') }}" class="text-decoration-none"><small>没有账号？点此注册</small></a>
    </form>
{% endblock %}

templates/front/front_profile.html
{% extends 'front/front_user_base.html' %}

{% block content %}
    {% set user = g.front_user %}
    <table class="table table-bordered">
        <tbody>
        <tr>
            <td>用户名:</td>
            <td>{{ user.username }}</td>
        </tr>
        <tr>
            <td>工号:</td>
            <td>{{ user.DL_ID }}</td>
        </tr>
        <tr>
            <td>角色:</td>
            <td>暂未开放</td>
        </tr>
        <tr>
            <td>权限:</td>
            <td>暂未开放</td>
        </tr>
        <tr>
            <td>加入时间:</td>
            <td>{{ user.join_time }}</td>
        </tr>
        </tbody>
    </table>
{% endblock %}

templates/front/front_user_base.html
{% extends 'front/front_base.html' %}

{% block nav_bar %}
    {{ super() }}
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{{ url_for('front.index') }}">Home</a>
        </li>
    </ul>
{% endblock %}
{% block nav_bar_right %}
    <li class="nav-item"><a class="nav-link active" aria-current="page"
                            href="{{ url_for('front.profile') }}">{{ g.front_user.username }}</a></li>
    <li class="nav-item"><a class="nav-link active" aria-current="page" href="{{ url_for('front.logout') }}">注销</a></li>
{% endblock %}
{% block content %}
    <div class="row">
        <ul class="nav flex-column col-2">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button"
                   aria-expanded="false">个人中心</a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="#">Action</a></li>
                    <li><a class="dropdown-item" href="#">Another action</a></li>
                    <li><a class="dropdown-item" href="#">Something else here</a></li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item" href="#">Separated link</a></li>
                </ul>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled">Disabled</a>
            </li>
        </ul>
        <ul class="col-10">
            11111111111111111111111111111111
        </ul>
    </div>
{% endblock %}