apps/cms/models.py
from exts import db
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash


class CMSUser(db.Model):
    __tablename__ = 'cms_user'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    username = db.Column(db.String(50), nullable=False)
    _password = db.Column(db.String(200), nullable=False)
    DL_ID = db.Column(db.String(6), nullable=False, unique=True)
    join_time = db.Column(db.DateTime, default=datetime.now())

    def __init__(self, username, password, DL_ID):
        self.username = username
        self.password = password
        self.DL_ID = DL_ID

    # 可以将一个类中的方法定义成属性
    @property
    def password(self):
        return self._password

    @password.setter
    def password(self, raw_password):
        self._password = generate_password_hash(raw_password)

    def check_password(self, raw_password):
        result = check_password_hash(self.password, raw_password)
        return result

# 密码：对外的字段名叫做password，对内使用的字段名叫_password

apps/cms/forms.py
from wtforms import Form, StringField, PasswordField, SubmitField, IntegerField
from wtforms.validators import data_required, InputRequired, Length, EqualTo
from apps.forms import BaseForm


class LoginForm(BaseForm):
    DL_ID = StringField(
        validators=[data_required(message='请输入工号'), InputRequired(message='请输入工号'), Length(6, message='请输入6位工号')])
    password = PasswordField(validators=[data_required('请输入密码'), Length(6, 20, message='请输入6-20位密码')])
    remember = IntegerField()
    submit = SubmitField()


class ResetpwdForm(BaseForm):
    oldpwd = PasswordField(validators=[data_required('请输入密码1'), Length(6, 20, message='请输入6-20位密码')])
    newpwd = PasswordField(validators=[data_required('请输入密码2'), Length(6, 20, message='请输入6-20位新密码')])
    newpwd2 = PasswordField(
        validators=[data_required('请输入密码3'), Length(6, 20, message='请输入6-20位新密码'),
                    EqualTo("newpwd", message="确认密码与新密码保持一致")])

apps/cms/__init__.py
import apps.cms.hooks

apps/cms/views.py
from flask import (Blueprint,
                   views,
                   render_template,
                   request,
                   session,
                   redirect,
                   url_for,
                   flash,
                   g,
                   jsonify)
from .forms import LoginForm, ResetpwdForm
from .models import CMSUser
from .decorators import login_required
import config
from exts import db

# 创建蓝图，指定子域名
# cms_bp = Blueprint('cms', __name__, subdomain='css')
cms_bp = Blueprint('cms', __name__, url_prefix='/cms')


@cms_bp.route('/')
@login_required
def index():
    # g.cms_user
    return render_template('cms/cms_index.html')


@cms_bp.route('/logout/')
@login_required
def logout():
    del session[config.CMS_USER_ID]
    # session.clear()
    return redirect(url_for('cms.login'))


@cms_bp.route('/profile/')
@login_required
def profile():
    return render_template('cms/cms_profile.html')


class LoginView(views.MethodView):
    def get(self, message=None):
        # flash(message)
        return render_template('cms/cms_login.html', message=message)

    def post(self):
        form = LoginForm(request.form)
        if form.validate():
            DL_ID = form.DL_ID.data
            password = form.password.data
            remember = form.remember.data
            user = CMSUser.query.filter_by(DL_ID=DL_ID).first()
            if user and user.check_password(password):
                session[config.CMS_USER_ID] = user.id
                if remember:
                    # 如果设置记住我，session.permanent = True
                    # 那么cookie过期时间31天
                    session.permanent = True
                return redirect(url_for('cms.index'))
            else:
                return self.get(message='工号或者密码错误')
        else:
            print(form.errors)
            # ('password',['请输入6-20位密码'])
            message = form.get_error()
            return self.get(message=message)


class ResetPwdView(views.MethodView):
    decorators = [login_required]

    def get(self):
        return render_template('cms/cms_resetpwd.html')

    def post(self):
        form = ResetpwdForm(request.form)
        if form.validate():
            oldpwd = form.oldpwd.data
            newpwd = form.newpwd.data
            user = g.cms_user
            if user.check_password(oldpwd):
                user.password = newpwd
                db.session.commit()
                # ("code":200,message="密码错误")
                return jsonify({"code": 200, "message": ""})
            else:
                return jsonify({"code": 400, "message": "旧密码错误"})

        else:
            message = form.get_error()
            print(message)
            return jsonify({"code": 400, "message": message})


cms_bp.add_url_rule('/login/', view_func=LoginView.as_view('login'))
cms_bp.add_url_rule('/resetpwd/', view_func=ResetPwdView.as_view('resetpwd'))

templates/cms/cms_base.html
{% from 'common/_macros.html' import static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>
        {% block title %}
        {% endblock %}
    </title>
{#    <meta name="csrf-token" content="sdfasdfasdf">#}
    <script src="http://cdn.bootcss.com/jquery/3.1.1/jquery.min.js"></script>
    <link href="http://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    {#    <script src="../js/common/zlajax.js"></script>#}
    <link href="{{ static('cms/css/base.css') }}" rel="stylesheet"/>
    <script src="{{ static('cms/js/base.js') }}"></script>
    <script src="{{ static('common/lrcajax.js') }}"></script>
    {% block head %}
    {% endblock %}
</head>

<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">11:40 CMS管理系统</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">{{ g.cms_user.username }} <span>[超级管理员]</span></a></li>
                <li><a href="{{ url_for('cms.logout') }}">注销</a></li>
            </ul>
            <form class="navbar-form navbar-right">
                <input type="text" class="form-control" placeholder="查找...">
            </form>
        </div>
    </div>
</nav>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav-sidebar">
                <li class="unfold">
                    <a href="#">首页</a>
                </li>
                <li class="profile-li">
                    <a href="#">个人中心 <span></span></a>
                    <ul class="subnav">
                        <li><a href="{{ url_for('cms.profile') }}">个人信息</a></li>
                        <li><a href="{{ url_for('cms.resetpwd') }}">修改密码</a></li>
                    </ul>
                </li>
                <li class="nav-group banner-manage">
                    <a href="#">日志管理</a>
                </li>
                <li class="nav-group post-manage">
                    <a href="#">帖子管理</a>
                </li>
                <li class="comments-manage">
                    <a href="#">评论管理</a>
                </li>
                <li class="board-manage">
                    <a href="#">板块管理</a>
                </li>
                <li class="nav-group cmsuser-manage">
                    <a href="#">用户管理</a>
                </li>
                <li class="nav-group cmsrole-manage">
                    <a href="#">员工管理</a>
                </li>
            </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <h1>{% block page_title %}{% endblock %}</h1>
            <div class="main_content">
                {% block main_content %}{% endblock %}
            </div>
        </div>
    </div>
</div>
</body>

</html>

templates/cms/cms_index.html
{% extends 'cms/cms_base.html' %}
{% block title %}
    11:40 CMS管理系统
{% endblock %}
{% block page_title %}
    欢迎来到11:40 CMS管理系统
{% endblock %}

templates/cms/cms_login.html
<!doctype html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <link rel="canonical" href="https://getbootstrap.com/docs/3.4/examples/signin/">

    <title>登录 11:40 CMS管理系统</title>

    <!-- Bootstrap core CSS -->
    <link href="https://fastly.jsdelivr.net/npm/@bootcss/v3.bootcss.com@1.0.30/dist/css/bootstrap.min.css"
          rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="https://fastly.jsdelivr.net/npm/@bootcss/v3.bootcss.com@1.0.30/examples/signin/signin.css"
          rel="stylesheet">

</head>

<body>

<div class="container">

    <form class="form-signin" method="post">
        <h2 class="form-signin-heading">请登录</h2>
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
        <label for="inputDL_ID" class="sr-only">工号</label>
        <input type="text" id="inputDL_ID" class="form-control" placeholder="工号" name="DL_ID" required autofocus>
        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" id="inputPassword" class="form-control" placeholder="密码" name="password" required>
        {% if message %}
            <p class="text-danger" style="text-align:center">{{ message }}</p>
        {% endif %}
        <div class="checkbox">
            <label>
                <input type="checkbox" value="1" name="remember"> 记住我
            </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">登录</button>
    </form>


</div> <!-- /container -->


</body>
</html>

templates/cms/cms_profile.html
{% extends 'cms/cms_base.html' %}
{% block title %}
    个人信息
{% endblock %}
{% block page_title %}
    {{ self.title() }}
{% endblock %}
{% block main_content %}
    {% set user = g.cms_user %}
    <table class="table table-bordered">
        <tbody>
        <tr>
            <td>用户名:</td>
            <td>{{ user.username }}</td>
        </tr>
        <tr>
            <td>工号:</td>
            <td>{{ user.DL_ID }}</td>
        </tr>
        <tr>
            <td>角色:</td>
            <td>暂未开放</td>
        </tr>
        <tr>
            <td>权限:</td>
            <td>暂未开放</td>
        </tr>
        <tr>
            <td>加入时间:</td>
            <td>{{ user.join_time }}</td>
        </tr>
        </tbody>
    </table>
{% endblock %}

templates/cms/cms_resetpwd.html
{% extends 'cms/cms_base.html' %}
{% from 'common/_macros.html' import static %}
{% block title -%}
    修改密码
{%- endblock %}

{% block page_title %}
    {{ self.title() }}
{% endblock %}

{% block head %}
    <style>
        .form-container {
            width: 300px;
        }
    </style>
    <script src="{{ static('cms/js/resetpwd.js') }}"></script>
{% endblock %}

{% block main_content %}
    <form action="" method="post">
        <div class="form-container">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
            <div class="form-group">
                <div class="input-group">
                    <div class="input-group-addon">旧密码</div>
                    <input type="password" class="form-control" id="exampleInputAmount" placeholder="请输入旧密码"
                           name="oldpwd">
                </div>
            </div>
            <div class="form-group">
                <div class="input-group">
                    <div class="input-group-addon">新密码</div>
                    <input type="password" class="form-control" id="exampleInputAmount" placeholder="请输入新密码"
                           name="newpwd">
                </div>
            </div>
            <div class="form-group">
                <div class="input-group">
                    <div class="input-group-addon">确认新密码</div>
                    <input type="password" class="form-control" id="exampleInputAmount" placeholder="请确认新密码"
                           name="newpwd2">
                </div>
            </div>
            <div class="form-group">
                <button id="submits" type="submit" class="btn btn-primary" name="submit">保存</button>
            </div>
        </div>
    </form>
{% endblock %}